scubs_api.cube_all:
    path:  /cubes.{_format}
    defaults: { _controller: ScubsApiBundle:Cube:all, _format: ~ }
    requirements:
        _method: GET

scubs_api.game_all:
    path:  /users/{userId}/games.{_format}
    defaults: { _controller: ScubsApiBundle:Game:all, _format: ~ }
    requirements:
        _method: GET

scubs_api.game:
    path:  /users/{userId}/games/{gameId}.{_format}
    defaults: { _controller: ScubsApiBundle:Game:game, _format: ~ }
    requirements:
        _method: GET

scubs_api.game.new:
    path:  /users/{userId}
    defaults: { _controller: ScubsApiBundle:Game:createGame }
    requirements:
        _method: POST

scubs_api.game.join:
    path:  /users/{userId}/games/{gameId}/join
    defaults: { _controller: ScubsApiBundle:Game:joinGame }
    requirements:
        _method: PUT

scubs_api.game.deny:
    path:  /users/{userId}/games/{gameId}/deny
    defaults: { _controller: ScubsApiBundle:Game:denyGame }
    requirements:
        _method: PUT

scubs_api.game.play:
    path:  /users/{userId}/games/{gameId}/turns/{x}/{y}/{z}
    defaults: { _controller: ScubsApiBundle:Game:playTurn }
    requirements:
        _method: POST