export const GAMES_PAGE_STATE = 'GAMES_PAGE_STATE';
export const PLAY_PAGE_STATE = 'PLAY_PAGE_STATE';
export const PROFILE_PAGE_STATE = 'PROFILE_PAGE_STATE';
export const SCORES_PAGE_STATE = 'SCORES_PAGE_STATE';