Scubs\CoreDomain\Cube\Cube:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            inline: true
        texture:
            expose: true
            serialized_name: texture
        thumbnail:
            expose: true
            serialized_name: thumbnail
        rarity:
            expose: true
            serialized_name: rarity
        description:
            expose: true
            serialized_name: name